### ISSUE TITLE
Refactor elements from unit-ri

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-tools#2]
Some elements currently in unit-ri, like JSON files under /test/resources or tool and helper classes (also there) should be moved here.

**Comment by wick3dshadow** [comment]
If my udnerstanding is not wrong the basic task is to remove the dependency of JSON files under /test/resource folder  from unit-ri to uom-tools.

**Comment by keilw** [comment]
Sort of yes. The JSON files were temporarily there in absence of a "real" project for them, but they currently do not feed JUnit tests, thus they were displaced in RI/test. uom-tools is meant to generate artifacts from e.g. such a JSON file, that could be Java classes, Properties or other formats. That's why a separate project feels better suited.
